# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.0
  # - 1.1
  # - 1.2
  # - 1.3
  - 1.4
  - nightly

codecov: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("ThreeBodyProblem")); include(joinpath("docs", "make.jl"))'
  # - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token  # Set in the settings page of your repository, as a secure variable
  local_dir: docs/build
  on:
    branch: master
